spring:
  application:
    name: mini-projecto-4-compose

  datasource:
    url: jdbc:postgresql://localhost:5432/neondb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: minha-chave-super-secreta
  expiration: 864000000

server:
  port: 3000